// AUTO-GENERATED by scripts/generate-kyc-keypair.cjs
// Do not edit by hand. Re-run the script to rotate.
// This is the PUBLIC half of the KYC data-key wrapping keypair.
// Safe to commit and ship to the browser.
export const KYC_PUBLIC_KEY_PEM = `-----BEGIN PUBLIC KEY-----
MIIBojANBgkqhkiG9w0BAQEFAAOCAY8AMIIBigKCAYEAmwZd6hzNSgAkQVA8ul1X
CMJ3R4XI4GEj47mGoNaeASalld1LoO+MGB0CKk2EqWbsT8WIM+jPzNZbNP8l4w1f
q2GxL3IjQvDePc0LlKNrLPvbCWWeHebkyzarxAdP/RJtS7pU+fLhT2J7zU+zyr2J
nqq7Smk/lgk5x9mIogJHFaUOGTYnX6gTp9y8eSiGnk1TGGNUTVn8DIvJtGCE/Blp
pWwvWi/FNleaDpmf60UkJZnYR1QmpxsjRD6NuFUNQtWG0NcDrUYtFpXTi0tzb/7e
+Dx3KsPnKKDgBBXstePfIkBEaLdkcPyiqfOikw6oRiPCXOul5dhQOdIDezEyc27T
A2ceT0sg2NYXU0eian/2IdVKInsF1MgJv7z2kzuB4H883iaN9VF8qr0kpPt5Gmno
LME72zAHkpHUUvvLcQ5gkfijmLjU4VSTaaECo3iBBd+ac1C4lpaoVf2pCsIEKSDu
MtAryqusIG0kn3qRSJ6DjVnBP/S5pJ0nVm4tmyVPcdANAgMBAAE=
-----END PUBLIC KEY-----`;

// Matches the key size / hash used on the server side.
export const KYC_WRAP_ALG = { name: 'RSA-OAEP', hash: 'SHA-256' };
